### ISSUE TITLE
Update drupal homepage tests

### ISSUE THREAD

**Issue by bitamar** [Gizra/haskala#112]

**Comment by DavidGizra** [comment]
@bitamar - Please update the issue about what is change.
Like this i can track on the changes.

**Comment by amitaibu** [comment]
@DavidGizra you can install the master - verify what changed, and add/update tests

**Comment by DavidGizra** [comment]
@amitaibu - I do it anyway, my intention was for future missions.
Sorry it was not clear.

**Comment by DavidGizra** [comment]
@bitamar and @miri ,

It ok the we do not have a PLACES link when the user it not login?

Drupal homepage image
![haskala header](https://cloud.githubusercontent.com/assets/5812423/5958604/fca85c74-a7ce-11e4-8985-bcb4ce0a41c7.png)

Jkeyll hompage image:
![jekll](https://cloud.githubusercontent.com/assets/5812423/5958656/8bdf6bda-a7cf-11e4-8a7a-363a675aa074.png)

**Comment by bitamar** [comment]
The places link should be shown

**Comment by miri** [comment]
We need to give access for the new solr search and check if the search link is correct for it.

**Comment by DavidGizra** [comment]
@bitamar and @miri ,
Let me know when you finish whit that, and i will check the design agin.

**Comment by bitamar** [comment]
@DavidGizra - Ready for you

**Comment by DavidGizra** [comment]
@bitamar -

![homp page](https://cloud.githubusercontent.com/assets/5812423/6017655/e2e08be0-ab98-11e4-9a21-053a18e743ce.png)

I will fix it.

**Comment by bitamar** [comment]
Fixed with branch 138-1
