### ISSUE TITLE
Implement places page

### ISSUE THREAD

**Issue by bitamar** [Gizra/haskala#125]
- Same as books and people pages. Display teasers of City nodes

**Comment by HelenaEksler** [comment]
@bitamar Should I wait for merging of #116 #121 #122 ? Or checkout from #122 ?

**Comment by bitamar** [comment]
Please continue from 122

**Comment by HelenaEksler** [comment]
@bitamar We don't have City nodes. We have only City taxonomy terms.

**Comment by bitamar** [comment]
Right, I forgot. So we need the same, but for city terms.
