### ISSUE TITLE
Link does not match the content

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/haskala#154]
When i enter in the admin to book content i see wrong url.

Add a image to content that i pick from book content type:
![book admin](https://cloud.githubusercontent.com/assets/5812423/6043618/132936e6-ac96-11e4-9ebe-56ee9c14f14a.png)
![books page error](https://cloud.githubusercontent.com/assets/5812423/6043619/17c6deb0-ac96-11e4-8a92-26531f3a03fa.png)

**Comment by bitamar** [comment]
@DavidKohav - I changed the book urls from /content/[title] to /books/[title] on purpose. Why is it a problem?
