### ISSUE TITLE
Minor behat fixes

### ISSUE THREAD

**Issue by amitaibu** [Gizra/haskala#169]
* https://github.com/Gizra/haskala/blob/master/behat/features/homepage-drupal.feature#L6 - remove ``@foo``
* Remove - https://github.com/Gizra/haskala/blob/master/behat/features/homepage-drupal.feature#L9

**Comment by DavidKohav** [comment]
@amitaibu - for your second comment,
' When  I visit "" ' - with nothing, sends me to the home page.
and i check the home page.

**Comment by amitaibu** [comment]
So change to ``When I visit "/"``

**Comment by DavidKohav** [comment]
@amitaibu - Done.
