### ISSUE TITLE
Fix breadcrumbs test

### ISSUE THREAD

**Issue by bitamar** [Gizra/haskala#177]
In book.feature
```
Then  I should see "1" ".bread-crumbs" elements
And   I should see the text "<text>"
```
This test doesn't verify that the text is inside the .bread-crumb element. 
It should be instead something like:
 ```Then  I should see "1" ".bread-crumbs" elements containing the text "<text>"```

**Comment by bitamar** [comment]
@DavidKohav - Same goes for person.feature

**Comment by DavidKohav** [comment]
@bitamar - You are confusing two things that are tested.

The Then  I should see "1" ".bread-crumbs" elements - just check if we have the class and we do not check something inside.

The And   I should see the text "<text>" - Check if we have the text that we expect in the page and not belong to the bread-crumb.

Do you want me to add one more test that checks what is in the class of the bread - crumb ?

**Comment by DavidKohav** [comment]
@bitamar - Done.
