### ISSUE TITLE
Missing "Digital books" link in the header 

### ISSUE THREAD

**Issue by bitamar** [Gizra/haskala#187]
![screen shot 2015-02-11 at 17 56 39](https://cloud.githubusercontent.com/assets/2283680/6150346/7954a956-b217-11e4-8343-4b24a6f385b2.png)

@miri - The header should contain a "Digital books" link, as the footer does. Please add and update the tests.

**Comment by miri** [comment]
The design hasn't "Digital books" link in header. 
Add anyway?

**Comment by bitamar** [comment]
Please do. It's a mistake in the design.
