### ISSUE TITLE
Fields missing in Haskala tables

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#220]
Hi @niryariv ,
List of fields missing in Haskala tables:

Type of book::
1. Is there information to contradict this? (under "Text is presented as original" )
2. References  (under "Text is presented as original" )
3. Notes  (under "Text is presented as original" )
4. Was the text expanded in translations?  (under "Text is presented as original" )
5. Was the text expanded in a new edition?  (under "Text is presented as original" )
6. Text is presented as a translation?
7. Is there information to contradict this?
8. References
9. Notes
10. Text is presented as a new edition?
11. Is there information to contradict this?
12. References
13. Name of "old text"
14. Author of "old text"
15. Notes
16. Quotes from Jewish sources
17. Quotes from non-Jewish sources
18. General notes

Translation:
19. Type of translation
20. Type of original text
21. Title of the original text as it appeared originally
22. Title of the original text as it appears elsewhere
23. References for title of the original text as it appears elsewher
24. Bibliographical citations
25. Original language of text (possible take by code) 
26. Year of publication of original text (possible take by code from "Year of publication as it appears in the book" of the referenced book ?)
27. Original publisher (possible take by code)
28. Place of publication of original text (possible take by code from "Place of publication as it appears in the book" of the referenced book ?)
29. Name of author of the original text as it appeared originally
30. Name of author of the original text as it appears elsewhere
31. References for name of author of the original text as it appears elsewhere

New edition:
32. Type of new edition, as specified in the text
33. References
34. Notes
35. Type of new edition, as specified elsewhere
36. References
37. Notes
38. Name of the old text as it appears in the book
39. Name of the old text's author as it appears in the book
40. Additional names for the old text's author as it appears in the book
41. Name of the old text's author as it appears in other sources
42. General notes

Volumes:
43. Number of examined volume
44. Names of planned volumes that were not published
45. Part of a series of books? (Probably unneeded because there is exist field: "name of series")
46. Printed originally with other books?
47. Names of other books

Publisher/ Printing press:
48. Price of book as it appears in the book
49. Year of publication as it appears in other sources
50. Hebrew year of publication as it appears in other sources
51. Gregorian year of publication as it appears in other sources
52. Place of publication as it appears in other sources
53. References
54. Notes

Book structure:
55. Occasional words in other languages
56. Notes (After "Is there a preface?")
57. Notes (After "Is there an epilogue?")
58. Notes (After "Is there a table of contents?")
59. Illustrations / diagrams
60. Notes on illustrations / diagrams
61. Pages in which illustrations / diagrams appear

Persons mentioned in book:
62. Notes (After "Are there rabbinical approbations?")
63. Notes (After "Are there recommendations?")
64. Notes (After "Are there thanks?")
65. Notes (After "Is there an appeal to sell subscriptions?")
66. Notes (After "Is there a list of subscribers?")
67. Notes (After "Is there a list of printers?")
68. Notes (After "Is there a list of proofreaders?")
69. Notes (After "Is there a list of the book's funders?")
70. Notes (After "Is there a list of the book's sellers?")
71. General notes

Textual models:
72. Main textual models of the book
73. Secondary textual models

Topics:
74. Notes

Target audience:
75. Contacts with other people
76. Contacts with official agents
77. Contemporary disputes about the book
78. Censorship
79. Bans
80. References (After "Later references to the book")
81. Original sources which mention the book
82. Mentions in reviews
83. Partial publication of the book in other texts

Catalog numbers:
84. Tel-Aviv University Library
85. National Library of Berlin catalog number
86. Widener Library, Harvard
87. The New York Public Library
88. British Library
89. Other libraries
90. Book is not available?
91. Notes on book availability

References and bibliography
92. Studies about the book

And the opposite: https://github.com/Gizra/haskala/issues/203

**Comment by bitamar** [comment]
Fixed on #243
