### ISSUE TITLE
Search icon - Hover state

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/haskala#226]
I do not see the hover color like the rest of the links.

Add a image to show the problem:

![search icon](https://cloud.githubusercontent.com/assets/5812423/6325298/48c9a274-bb4e-11e4-9ca0-a24c2d37d6f8.png)

**Comment by bitamar** [comment]
@kerensoref - All buttons except of this one have an hover state. Do you want this one to also become blue-ish on hover?

**Comment by kerensoref** [comment]
Yes, that will be great. Should I provided an image or are you good?

**Comment by bitamar** [comment]
@kerensoref - Please create the image then. I don't know how to do it fast

**Comment by kerensoref** [comment]
https://www.dropbox.com/s/1d81g99xzj23ric/Search_hover.png.zip?dl=0

**Comment by bitamar** [comment]
Thanks Keren

![search_hover](https://cloud.githubusercontent.com/assets/2283680/6328102/6fdfdcf2-bb6c-11e4-86c0-0c40353bea99.png)

**Comment by DavidKohav** [comment]
@bitamar - When you hover on the icon, you have a delay .

**Comment by bitamar** [comment]
Fixed
