### ISSUE TITLE
Digital book link

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/haskala#228]
This link get 404 and not look like the rest of the links

Add a link to the page:
http://dev-haskala.pantheon.io/books/%D7%90%D7%95%D7%A8-%D7%90%D7%A1%D7%AA%D7%A8-oder-beleuchtung-der-im-talmud-von-babylon-und-jerusalem-den-targumim-und-midraschim#publisher-printing-press

Add a image to show the problem:
![ddd](https://cloud.githubusercontent.com/assets/5812423/6325452/59f4dbe8-bb50-11e4-9753-6cd2ad15405f.png)

**Comment by bitamar** [comment]
- The link is now displayed in one row. 
- The 404 from the external site is out of our scope.
