### ISSUE TITLE
Editions tab - Needless number 

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#258]
http://dev-haskala.pantheon.io/books/%D7%93%D7%91%D7%A8%D7%99-%D7%A9%D7%9C%D7%95%D7%9D-%D7%95%D7%90%D7%9E%D7%AA-%D7%90
![image](https://cloud.githubusercontent.com/assets/123744/6440704/89ec3cb8-c0e8-11e4-8b0e-5247640a3ce1.png)

**Comment by bitamar** [comment]
Duplicate of #254
