### ISSUE TITLE
Empty fields

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#265]
1. New edition - Name of the old text's author as it appears in other sources
2. Book structure - Notes on illustrations/diagrams
3. Book structure - illustrations/diagrams
4. Target audience - References for mentions
5. Type of book - Is there information to contradict this? (Information to contradict translation)

**Comment by bitamar** [comment]
There are 15 records in the xml for "Name of the old text's author as it appears in other sources". I'll update the csv.

**Comment by bitamar** [comment]
Ignore my comment above. I was looking at "Name of the old text's author as it appears in the book" instead.  "Name of the old text's author as it appears in other sources" seems to be empty also on the xml export.

**Comment by DavidKohav** [comment]
Book producers
1. References
2. Current name of location
3. Location during writing of book
4. Religion during writing of book
5. Approximate age during writing of book
6. Evidence for person's identity if it does not appear in the book
7. Name as it appears in the book
8. Does the person's name appear in the book?

**Comment by DavidKohav** [comment]
Catalog number
1. Berlin State Library
2. The New York Public Library			
3. Widener Library, Harvard	
4. British Library		
5. Notes on book availability
