### ISSUE TITLE
Multi prefaces

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#270]
There are (or only one) books that have multi prefaces.
ie: ספר עמוד השחר.

http://haskala.referata.com/wiki/%D7%A1%D7%A4%D7%A8_%D7%A2%D7%9E%D7%95%D7%93_%D7%94%D7%A9%D7%97%D7%A8#tab=Prefaces

http://dev-haskala.pantheon.io/books/%D7%A1%D7%A4%D7%A8-%D7%A2%D7%9E%D7%95%D7%93-%D7%94%D7%A9%D7%97%D7%A8#prefaces

**Comment by bitamar** [comment]
Books with multiple prefaces:

http://haskala.referata.com/w/index.php?title=Special:SearchByProperty&offset=0&limit=500&property=Number+of+preface&value=2

Abhandlung von der Freiheit des Menschen  + (2)
Hinterlassene Gedichte 1  + (2)
אבטליון  + (2)
אגדת ארבע כוסות  + (2)
בנות השיר  + (2)
מגלת חסידים א  + (2)
משלי אסף ג  + (2)
ספר בית נאמן  + (2)
ספר הגדרים  + (2)
ספר המדות א  + (2)
ספר חכמת שלמה  + (2)
ספר יסוד מורא  + (2)
ספר מנחה טהורה  + (2)
ספר מצפה יקתאל  + (2)
ספר נאוה קדש  + (2)
ספר עמוד השחר  + (2)
ספר רפואת העם  + (2)
ספר שאלות ותשובות בשמים ראש  + (2)
ספר תהלים  + (2)
ספר תפארת אדם  + (2)
ראשית למודים א  + (2)
תורת לשון עברית ב  + (2)
ראשית למודים א  + (1)

http://haskala.referata.com/w/index.php?title=Special:SearchByProperty&offset=0&limit=500&property=Number+of+preface&value=3

הקולות יחדלון או משפט שלום  + (3)
לישרים תהלה  + (3)
ספר מנחה טהורה  + (3)
ספר מעדני מלך  + (3)
פרקי רבי עקיבא  + (3)
שירי תפארת ד  + (3)
