### ISSUE TITLE
import books data

### ISSUE THREAD

**Issue by niryariv** [Gizra/haskala#4]
select "CSV Export"

http://haskala.referata.com/w/index.php?title=Special%3AAsk&q=%5B%5BCategory%3ABooks%5D%5D&po=%3FAlignment%C2%A0of%C2%A0text%0D%0A%3FAre%C2%A0there%C2%A0dedications%0D%0A%3FAre%C2%A0there%C2%A0illustrations%2Fdiagrams%0D%0A%3FAre%C2%A0there%C2%A0personal%C2%A0addresses%0D%0A%3FAre%C2%A0there%C2%A0rabbinical%C2%A0approbations%0D%0A%3FAre%C2%A0there%C2%A0recommendations%0D%0A%3FAre%C2%A0there%C2%A0sources%C2%A0mentioned%C2%A0in%C2%A0the%C2%A0book%C2%A0itself%0D%0A%3FAre%C2%A0there%C2%A0thanks%0D%0A%3FContemporary%C2%A0references%C2%A0to%C2%A0the%C2%A0book%0D%0A%3FCopy%C2%A0of%C2%A0book%C2%A0used%0D%0A%3FEvidence%C2%A0about%C2%A0book%C2%A0production%0D%0A%3FFonts%0D%0A%3FFormat%C2%A0of%C2%A0publication%C2%A0date%0D%0A%3FFormatted%C2%A0display%C2%A0title%0D%0A%3FFrankfurt%C2%A0University%C2%A0Library%C2%A0catalog%C2%A0number%0D%0A%3FFull%C2%A0title%0D%0A%3FGregorian%C2%A0year%C2%A0of%C2%A0publication%C2%A0as%C2%A0it%C2%A0appears%C2%A0in%C2%A0the%C2%A0book%0D%0A%3FHebrew%C2%A0year%C2%A0of%C2%A0publication%C2%A0as%C2%A0it%C2%A0appears%C2%A0in%C2%A0the%C2%A0book%0D%0A%3FHeight%C2%A0of%C2%A0book%2C%C2%A0in%C2%A0cm%0D%0A%3FIs%C2%A0there%C2%A0a%C2%A0list%C2%A0of%C2%A0funders%0D%0A%3FIs%C2%A0there%C2%A0a%C2%A0list%C2%A0of%C2%A0printers%0D%0A%3FIs%C2%A0there%C2%A0a%C2%A0list%C2%A0of%C2%A0proofreaders%0D%0A%3FIs%C2%A0there%C2%A0a%C2%A0list%C2%A0of%C2%A0sellers%0D%0A%3FIs%C2%A0there%C2%A0a%C2%A0list%C2%A0of%C2%A0subscribers%0D%0A%3FIs%C2%A0there%C2%A0a%C2%A0preface%0D%0A%3FIs%C2%A0there%C2%A0a%C2%A0table%C2%A0of%C2%A0contents%0D%0A%3FIs%C2%A0there%C2%A0an%C2%A0appeal%C2%A0to%C2%A0sell%C2%A0subscriptions%0D%0A%3FIs%C2%A0there%C2%A0an%C2%A0epilogue%0D%0A%3FLanguage%C2%A0in%C2%A0book%0D%0A%3FLanguage%C2%A0of%C2%A0footnotes%0D%0A%3FLast%C2%A0known%C2%A0edition%0D%0A%3FLater%C2%A0references%C2%A0to%C2%A0the%C2%A0book%0D%0A%3FLibrary+of+Bar+Ilan+University+catalog+number%0D%0A%3FLink%C2%A0to%C2%A0digital%C2%A0book%0D%0A%3FList%C2%A0of%C2%A0sources%C2%A0mentioned%C2%A0in%C2%A0the%C2%A0book%0D%0A%3FLocation%C2%A0of%C2%A0footnotes%0D%0A%3FMotto%0D%0A%3FName%C2%A0of%C2%A0publisher%0D%0A%3FName+of+series%0D%0A%3FNames+of+other+published+volumes%0D%0A%3FNational%C2%A0Library%C2%A0of%C2%A0Berlin%C2%A0catalog%C2%A0number%0D%0A%3FNational%C2%A0Library%C2%A0of%C2%A0Hebrew%C2%A0University%C2%A0catalog%C2%A0number%0D%0A%3FNotes%C2%A0on%C2%A0book%C2%A0structure%0D%0A%3FNotes+on+catalog+numbers%0D%0A%3FNotes%C2%A0on%C2%A0dedications%0D%0A%3FNotes+on+personal+addresses%0D%0A%3FNotes%C2%A0on%C2%A0preface%0D%0A%3FNotes+on+references%0D%0A%3FNotes+on+target+audience%0D%0A%3FNotes+on+textual+models%0D%0A%3FNotes+on+volumes%0D%0A%3FNumber%C2%A0of%C2%A0examined%C2%A0volume%0D%0A%3FNumber%C2%A0of%C2%A0languages%0D%0A%3FNumber%C2%A0of%C2%A0pages%0D%0A%3FNumber%C2%A0of%C2%A0preface%0D%0A%3FNumber%C2%A0of%C2%A0volumes%C2%A0published%0D%0A%3FPlace%C2%A0of%C2%A0publication%C2%A0as%C2%A0it%C2%A0appears%C2%A0in%C2%A0the%C2%A0book%0D%0A%3FPreface%C2%A0title%0D%0A%3FReferences%C2%A0for%C2%A0editions%0D%0A%3FReferences%C2%A0for%C2%A0sources%C2%A0mentioned%C2%A0in%C2%A0the%C2%A0book%0D%0A%3FRole%C2%A0in%C2%A0book%C2%A0production%0D%0A%3FSecondary%C2%A0sources%C2%A0used%C2%A0by%C2%A0researchers%0D%0A%3FTarget%C2%A0audience%C2%A0as%C2%A0described%C2%A0in%C2%A0the%C2%A0book%0D%0A%3FText%C2%A0is%C2%A0presented%C2%A0as%C2%A0original%0D%0A%3FTitle+in+Latin+characters%0D%0A%3FTopic%0D%0A%3FTotal%C2%A0number%C2%A0of%C2%A0editions%0D%0A%3FTypography%0D%0A%3FWidth%C2%A0of%C2%A0book%2C%C2%A0in%C2%A0cm%0D%0A%3FWriter%C2%A0of%C2%A0preface%0D%0A%3FYear%C2%A0of%C2%A0publication%C2%A0as%C2%A0it%C2%A0appears%C2%A0in%C2%A0the%C2%A0book%0D%0A&eq=yes&p%5Bformat%5D=broadtable&sort_num=&order_num=ASC&p%5Blimit%5D=1000&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=%E2%80%A6+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&eq=yes

**Comment by bitamar** [comment]
Fixed books query:

http://haskala.referata.com/w/index.php?title=Special%3AAsk&q=%5B%5BCategory%3ABooks%5D%5D&po=%3FAlignment+of+text%0D%0A%3FAre+there+dedications%0D%0A%3FAre+there+illustrations%2Fdiagrams%0D%0A%3FAre+there+personal+addresses%0D%0A%3FAre+there+rabbinical+approbations%0D%0A%3FAre+there+recommendations%0D%0A%3FAre+there+sources+mentioned+in+the+book+itself%0D%0A%3FAre+there+thanks%0D%0A%3FContemporary+references+to+the+book%0D%0A%3FCopy+of+book+used%0D%0A%3FEvidence+about+book+production%0D%0A%3FFonts%0D%0A%3FFormat+of+publication+date%0D%0A%3FFormatted+display+title%0D%0A%3FFrankfurt+University+Library+catalog+number%0D%0A%3FFull+title%0D%0A%3FGregorian+year+of+publication+as+it+appears+in+the+book%0D%0A%3FHebrew+year+of+publication+as+it+appears+in+the+book%0D%0A%3FHeight+of+book%2C+in+cm%0D%0A%3FIs+there+a+list+of+funders%0D%0A%3FIs+there+a+list+of+printers%0D%0A%3FIs+there+a+list+of+proofreaders%0D%0A%3FIs+there+a+list+of+sellers%0D%0A%3FIs+there+a+list+of+subscribers%0D%0A%3FIs+there+a+preface%0D%0A%3FIs+there+a+table+of+contents%0D%0A%3FIs+there+an+appeal+to+sell+subscriptions%0D%0A%3FIs+there+an+epilogue%0D%0A%3FLanguage+in+book%0D%0A%3FLanguage+of+footnotes%0D%0A%3FLast+known+edition%0D%0A%3FLater+references+to+the+book%0D%0A%3FLibrary+of+Bar+Ilan+University+catalog+number%0D%0A%3FLink+to+digital+book%0D%0A%3FList+of+sources+mentioned+in+the+book%0D%0A%3FLocation+of+footnotes%0D%0A%3FMotto%0D%0A%3FName+of+publisher%0D%0A%3FName+of+series%0D%0A%3FNames+of+other+published+volumes%0D%0A%3FNational+Library+of+Berlin+catalog+number%0D%0A%3FNational+Library+of+Hebrew+University+catalog+number%0D%0A%3FNotes+on+book+structure%0D%0A%3FNotes+on+catalog+numbers%0D%0A%3FNotes+on+dedications%0D%0A%3FNotes+on+personal+addresses%0D%0A%3FNotes+on+preface%0D%0A%3FNotes+on+references%0D%0A%3FNotes+on+target+audience%0D%0A%3FNotes+on+textual+models%0D%0A%3FNotes+on+volumes%0D%0A%3FNumber+of+examined+volume%0D%0A%3FNumber+of+languages%0D%0A%3FNumber+of+pages%0D%0A%3FNumber+of+preface%0D%0A%3FNumber+of+volumes+published%0D%0A%3FPlace+of+publication+as+it+appears+in+the+book%0D%0A%3FPreface+title%0D%0A%3FReferences+for+editions%0D%0A%3FReferences+for+sources+mentioned+in+the+book%0D%0A%3FRole+in+book+production%0D%0A%3FSecondary+sources+used+by+researchers%0D%0A%3FTarget+audience+as+described+in+the+book%0D%0A%3FText+is+presented+as+original%0D%0A%3FTitle+in+Latin+characters%0D%0A%3FTopic%0D%0A%3FTotal+number+of+editions%0D%0A%3FTypography%0D%0A%3FWidth+of+book%2C+in+cm%0D%0A%3FWriter+of+preface%0D%0A%3FYear+of+publication+as+it+appears+in+the+book%0D%0A&eq=yes&p%5Bformat%5D=broadtable&sort_num=&order_num=ASC&p%5Blimit%5D=1000&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=%E2%80%A6+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&eq=yes
