### ISSUE TITLE
Test all pages in ie

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/haskala#54]
Check the web site on ie 9 and 10

**Comment by DavidGizra** [comment]
@bitamar - Done.

**Comment by bitamar** [comment]
@DavidKohav - I merged the PR, but please verify also "book" and "books" pages on IE 9 and 10.

**Comment by DavidKohav** [comment]
@bitamar - Sure, I will do it.
please wait with the merge and comments, i didn't finish to work on all the issue.
