### ISSUE TITLE
Type of book tab

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#59]
See: 
http://haskala.referata.com/wiki/Abhandlung_von_der_Freiheit_des_Menschen#tab=Type_of_book

http://haskala.referata.com/wiki/Special:FormEdit/Book/t#tab=Type_of_book

**Comment by miri** [comment]
@knepper ,
Is edition is a book record itself or edition record reference to book?

**Comment by miri** [comment]
We don't put the fields: "Full title of book", "Text is presented as original", "Are there sources mentioned in the book itself"
in this tab because they appear in the top details of book by the new design.

**Comment by miri** [comment]
@knepper ,
If book is presented as a new edition, The fields: "Name of "old text":" ,"Author of "old text": " are of a old edittion or the orginal book?

**Comment by miri** [comment]
Hi @knepper , @niryariv, 
Is "Type of book" wiki tab by the new design appear only on the top of book page and not include in the tabs?
If yes - sometimes there is a lot of data.
If not - That fields that displayed in the top are displayed in the "Type of book" tab also?
![image](https://cloud.githubusercontent.com/assets/123744/6037279/906f4ca8-ac5a-11e4-8774-07504521d4e7.png)

**Comment by knepper** [comment]
We would like to keep on the top of the book page and not repeat it in the tab.

**Comment by miri** [comment]
Answers in 10.2.15 Conference Call :
1. Edition isn't record o book type.
2. If book is presented as a new edition, The fields: "Name of "old text":" ,"Author of "old text": " are regular text fields and not reference anything.
