### ISSUE TITLE
Translation tab

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#60]
See:
http://haskala.referata.com/wiki/Abhandlung_von_der_Freiheit_des_Menschen#tab=Translation

http://haskala.referata.com/wiki/Special:FormEdit/Book/t#tab=Translation

http://haskala.referata.com/wiki/Special:FormEdit/Book/t#tab=Type_of_book

**Comment by miri** [comment]
Hi @knepper,
In Translation tab view:
http://haskala.referata.com/wiki/Akten-St%C3%BCcke_die_Reform_der_J%C3%BCdischen_Kolonieen_in_den_Preu%C3%9Fischen_Staaten_betreffend#tab=Textual_models
 or create :
http://haskala.referata.com/wiki/Special:FormEdit/Book/t#tab=Translation

No appearance of the fildes: Year of translation, City of translation, Translator, References for translation.
It apear only under the Editions tab of the orginal book:
http://haskala.referata.com/wiki/%D7%93%D7%91%D7%A8%D7%99_%D7%A9%D7%9C%D7%95%D7%9D_%D7%95%D7%90%D7%9E%D7%AA_%D7%90#tab=Editions

Whether to add the above fields into Translation tab?

**Comment by miri** [comment]
Delete "Other names for the author" field. 
Take the data from person reference fields: Hebrew name, German Name, Pseudonym

**Comment by knepper** [comment]
-> Skype call
