### ISSUE TITLE
Volumes tab

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#62]
http://haskala.referata.com/wiki/Abhandlung_von_der_Freiheit_des_Menschen#tab=Volumes

http://haskala.referata.com/wiki/Special:FormEdit/Book/t#tab=Volumes

**Comment by miri** [comment]
Missing fields in csv book table:
1. Names of planned volumes that were not published:
2. Part of a series of books?
3.Printed originally with other books?
4. Names of other books:

**Comment by bitamar** [comment]
@miri - I assume we'll not re-create the books csv again, just make sure these fields can be edited manually.
