### ISSUE TITLE
Prefaces tab

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#66]
Role in book production of preface writer field

http://haskala.referata.com/wiki/Abhandlung_von_der_Freiheit_des_Menschen#tab=Prefaces

http://haskala.referata.com/wiki/Special:FormEdit/Book/t#tab=Prefaces

**Comment by miri** [comment]
@knepper, @niryariv, @bitamar 
Pay attention: the Writer of preface filed of book isn't match the person title in people csv, And therefore this information is lost.

For example: 
The writer of preface filed of "Abhandlung von der Freiheit des Menschen" book (the first line of books csv) is "אלכסנדר, יצחק", but in person.csv he is apear as "Alexander, Isaak - אלכסנדר, יצחק" (that data s taken from the producer table). 

Need to synchronize for prevent losing information.

**Comment by knepper** [comment]
We understand that it would preferable to have the same name string for both roles of the same person. However we don't understand why infomation would be lost.

Of course, if you could synchronize it will be best.
