### ISSUE TITLE
Catalog numbers tab

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#71]
missing fields

http://haskala.referata.com/wiki/Abhandlung_von_der_Freiheit_des_Menschen#tab=Catalog_numbers

http://haskala.referata.com/wiki/Special:FormEdit/Book/t#tab=Catalog_numbers

**Comment by miri** [comment]
@knepper , @niryariv :
the field General notes in Catalog numbers tab http://haskala.referata.com/wiki/Abhandlung_von_der_Freiheit_des_Menschen#tab=Catalog_numbers

is it the "Notes on catalog numbers" field that appear in the csv table?

**Comment by knepper** [comment]
Yes, this should be the same field.
