### ISSUE TITLE
Book producers tab

### ISSUE THREAD

**Issue by miri** [Gizra/haskala#73]
http://haskala.referata.com/wiki/Abhandlung_von_der_Freiheit_des_Menschen#tab=Book_producers

http://haskala.referata.com/wiki/Special:FormEdit/Book/t#tab=Book_producers

**Comment by DavidGizra** [comment]
The B latter not look good in the page title.

Add a link to the page:
http://localhost/haskala/www/books/%D7%A1%D7%A4%D7%A8-%D7%A2%D7%A6%D7%99-%D7%A2%D7%93%D7%9F

Add a image that show the issue:
![b](https://cloud.githubusercontent.com/assets/5812423/6040863/3c5bbeba-ac7f-11e4-8703-470677751a15.png)

**Comment by DavidGizra** [comment]
Missing bradcrums:

Add the link page:
http://localhost/haskala/www/books/%D7%A1%D7%A4%D7%A8-%D7%A2%D7%A6%D7%99-%D7%A2%D7%93%D7%9F

In the image you can see the right position that we do not have the bradcrums
![bradcrums](https://cloud.githubusercontent.com/assets/5812423/6040906/c1578c7a-ac7f-11e4-9482-caa3e1327bdb.png)

**Comment by DavidGizra** [comment]
All the tags need to show in one line and in the arrow you need to scroll to the next tags.

Add a image that show what i mean:
![arrow](https://cloud.githubusercontent.com/assets/5812423/6040993/ad5a4752-ac80-11e4-90da-f1ffcc4770bf.png)

**Comment by DavidGizra** [comment]
The line color not like in the design

Add a image that show what i mean:
![line color](https://cloud.githubusercontent.com/assets/5812423/6041041/27cc96a2-ac81-11e4-9ed9-f4ebfdad84d1.png)

**Comment by DavidGizra** [comment]
@bitamar - I will check whit behat if we have the tab.

**Comment by DavidGizra** [comment]
@bitamar -
I need that #154 issue to solve.
I do not know if i see the right thing.

**Comment by DavidGizra** [comment]
I did the behat test, Including #68 #65
